## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [1]:
import pandas as pd
file = "/Users/jenniferleone/Desktop/Git_Repositories/Assignments/Module_4_Challenge/pandas-challenge-1/Starter_Code/Resources/client_dataset.csv"
client_df = pd.read_csv(file)

client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,UCA28532-31-0B,software,logistics,83.13,51.60,2.25,33,8
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,EBD29277-23-7U,consumables,kitchen supplies,206.59,175.46,11.70,47,0
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,EBD30093-55-9Z,consumables,bathroom supplies,65.66,57.31,4.16,475,6
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,XMZ38239-49-3D,furniture,stands,1.48,1.22,18.04,112,0
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,ZCZ05589-50-5D,software,project management,3.01,1.61,2.07,1031,5

In [2]:
# View the column names in the data
client_df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [3]:
# Use the describe function to gather some basic statistics
client_df.describe()

,client_id,order_id,order_week,order_year,unit_price,unit_cost,unit_weight,qty,line_number
count,54639.000000,5.463900e+04,54639.000000,54639.000000,54639.000000,54639.000000,54639.000000,5.463900e+04,54639.000000
mean,54837.869416,5.470190e+06,11.359139,2022.993064,136.267207,99.446073,5.004116,5.702646e+02,2.979667
std,25487.438231,2.599807e+06,7.023499,0.082997,183.873135,133.164267,5.326599,1.879552e+04,2.436320
min,10033.000000,1.000886e+06,1.000000,2022.000000,0.010000,0.010000,0.000000,0.000000e+00,0.000000
25%,33593.000000,3.196372e+06,6.000000,2023.000000,20.800000,14.840000,1.450000,3.200000e+01,1.000000
50%,53305.000000,5.496966e+06,11.000000,2023.000000,68.310000,49.890000,3.240000,6.800000e+01,3.000000
75%,78498.000000,7.733869e+06,17.000000,2023.000000,173.160000,125.570000,6.890000,1.700000e+02,5.000000
max,99984.000000,9.998480e+06,52.000000,2023.000000,1396.230000,846.270000,46.430000,3.958244e+06,9.000000

In [4]:
# Use this space to do any additional research
# and familiarize yourself with the data.

# see following cells

In [5]:
# list of all the job types and counts of each
client_df['job'].value_counts()
# client_df['job'].nunique()

job
Osteopath                             631
Toxicologist                          546
Architectural technologist            430
Librarian, academic                   389
Teacher, special educational needs    388
                                     ...
Copywriter, advertising                12
Midwife                                10
Insurance risk surveyor                 9
Runner, broadcasting/film/video         9
Advertising account planner             5
Name: count, Length: 498, dtype: int64

In [6]:
# explore qty by category and subcategory

table = pd.pivot_table(client_df, values= ['qty'], index=['category',
       'subcategory'], aggfunc=["sum","min","max","mean"],fill_value=0, margins=True)
print(table)

                                     sum min      max         mean
                                     qty qty      qty          qty
category    subcategory
consumables bathroom supplies    2883256   0   236016   448.825654
            kitchen supplies     3293648   0   494692   573.207101
            misc                 1048196   0   109328   362.572120
            paper products       3107779   0   637318   529.073715
            pens                 2202348   0   842581   846.080676
decor       misc                  352794   0    17975   252.898925
            plants               1201913   0    64636   346.772360
            wall art             1484121   0   337758   479.832202
electronics audio visual          260206   0    24873   355.472678
            cabling               222736   0    24528   340.054962
            computers             247390   1    78611   529.743041
            telecom               884222   1   389960   904.112474
furniture   desks                 309194   1   156986   606.262745
            seating              1339512   0   140056   502.819820
            stands               5521319   0  3958244  1314.286836
            tables               3068302   0   977121   675.837445
software    accounting           1712305   0   204154   455.885250
            logistics             370018   0    45189   329.784314
            project management   1649429   0   224222   468.321692
All                             31158688   0  3958244   570.264610

In [7]:
# Verify total qty
client_df['qty'].sum()

31158688

In [8]:
# What three item categories had the most entries?
most_categories= client_df["category"].value_counts()
most_categories.head(3)

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64

In [9]:
# For the category with the most entries, "consumables"
# which subcategory had the most entries? 'bathroom supplies'
consumables_df = client_df[client_df.category == 'consumables']

consumables_subcategory = consumables_df['subcategory'].value_counts()

consumables_subcategory.head(1)

subcategory
bathroom supplies    6424
Name: count, dtype: int64

In [10]:
# Which five clients had the most entries in the data?

client_df['client_id'].value_counts().head(5)

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [11]:
# Store the client ids of those top 5 clients in a list.
top5_clients = ['33615','66037', '46820', '38378','24741']
print(top5_clients)

['33615', '66037', '46820', '38378', '24741']

In [12]:
# How many total units (the qty column) did the
# client with the most entries order?

top_client = client_df[client_df.client_id == 33615]
top_client_total = top_client['qty'].sum()

print(f'The client with the most entries ordered a total of {top_client_total} units')

The client with the most entries ordered a total of 64313 units

## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [13]:
# Create a column that calculates the 
# subtotal for each line using the unit_price
# and the qty
subtotal_price = client_df['unit_price'] * client_df['qty']
client_df["subtotal_price"] = subtotal_price
client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,subtotal_price
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1,115164.00
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0,523.95
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6,527.28
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3,1056.18
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1,3902.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,UCA28532-31-0B,software,logistics,83.13,51.60,2.25,33,8,2743.29
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,EBD29277-23-7U,consumables,kitchen supplies,206.59,175.46,11.70,47,0,9709.73
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,EBD30093-55-9Z,consumables,bathroom supplies,65.66,57.31,4.16,475,6,31188.50
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,XMZ38239-49-3D,furniture,stands,1.48,1.22,18.04,112,0,165.76
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,ZCZ05589-50-5D,software,project management,3.01,1.61,2.07,1031,5,3103.31

In [16]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound
# for orders over 50 pounds and $10 per
# pound for items 50 pounds or under.

# calculate total weight of order.
total_weight = client_df['unit_weight'] * client_df['qty']
client_df['total_weight'] = total_weight
client_df


client_df['shipping_price'] = client_df['total_weight'].apply(lambda x: x * 7 if x > 50 else x * 10)
client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,subtotal_price,total_weight,shipping_price
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,decor,wall art,1096.80,762.71,7.50,105,1,115164.00,787.50,5512.50
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,consumables,pens,24.95,15.09,1.49,21,0,523.95,31.29,312.90
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,software,project management,13.52,7.86,1.68,39,6,527.28,65.52,458.64
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,consumables,pens,36.42,24.85,1.23,29,3,1056.18,35.67,356.70
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,consumables,misc,195.10,108.17,46.43,20,1,3902.00,928.60,6500.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,software,logistics,83.13,51.60,2.25,33,8,2743.29,74.25,519.75
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,consumables,kitchen supplies,206.59,175.46,11.70,47,0,9709.73,549.90,3849.30
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,consumables,bathroom supplies,65.66,57.31,4.16,475,6,31188.50,1976.00,13832.00
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,furniture,stands,1.48,1.22,18.04,112,0,165.76,2020.48,14143.36
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,software,project management,3.01,1.61,2.07,1031,5,3103.31,2134.17,14939.19

In [20]:
# Create a column for the total price
# using the subtotal and the shipping price
# along with a sales tax of 9.25%

client_df['total_price'] = client_df['subtotal_price'] + client_df['shipping_price'] * 1.0925
client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_cost,unit_weight,qty,line_number,subtotal_price,total_weight,shipping_price,total_price,total_cost,profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,762.71,7.50,105,1,115164.00,787.50,5512.50,121186.406250,85597.05,-74434.473750
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,15.09,1.49,21,0,523.95,31.29,312.90,865.793250,629.79,-552.381375
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,7.86,1.68,39,6,527.28,65.52,458.64,1028.344200,765.18,-673.982400
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,24.85,1.23,29,3,1056.18,35.67,356.70,1445.874750,1077.35,-946.658600
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,108.17,46.43,20,1,3902.00,928.60,6500.20,11003.468500,8663.60,-7701.396500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,51.60,2.25,33,8,2743.29,74.25,519.75,3311.116875,2222.55,-1920.718800
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,175.46,11.70,47,0,9709.73,549.90,3849.30,13915.090250,12095.92,-10841.709725
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,57.31,4.16,475,6,31188.50,1976.00,13832.00,46299.960000,41054.25,-36889.853750
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.22,18.04,112,0,165.76,2020.48,14143.36,15617.380800,14280.00,-12956.406400
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,1.61,2.07,1031,5,3103.31,2134.17,14939.19,19424.375075,16599.10,-14930.168750

In [21]:
# Create a column for the cost
# of each line using unit cost, qty, and
# shipping price (assume the shipping cost
# is exactly what is charged to the client).
total_cost = (client_df['unit_cost'] * client_df['qty']) + client_df['shipping_price']
client_df['total_cost'] = total_cost
client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_cost,unit_weight,qty,line_number,subtotal_price,total_weight,shipping_price,total_price,total_cost,profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,762.71,7.50,105,1,115164.00,787.50,5512.50,121186.406250,85597.05,-74434.473750
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,15.09,1.49,21,0,523.95,31.29,312.90,865.793250,629.79,-552.381375
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,7.86,1.68,39,6,527.28,65.52,458.64,1028.344200,765.18,-673.982400
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,24.85,1.23,29,3,1056.18,35.67,356.70,1445.874750,1077.35,-946.658600
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,108.17,46.43,20,1,3902.00,928.60,6500.20,11003.468500,8663.60,-7701.396500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,51.60,2.25,33,8,2743.29,74.25,519.75,3311.116875,2222.55,-1920.718800
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,175.46,11.70,47,0,9709.73,549.90,3849.30,13915.090250,12095.92,-10841.709725
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,57.31,4.16,475,6,31188.50,1976.00,13832.00,46299.960000,41054.25,-36889.853750
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.22,18.04,112,0,165.76,2020.48,14143.36,15617.380800,14280.00,-12956.406400
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,1.61,2.07,1031,5,3103.31,2134.17,14939.19,19424.375075,16599.10,-14930.168750

In [22]:
# Create a column for the profit of
# each line using line cost and line price
profit = client_df['total_price'] - client_df['total_cost']
client_df['profit'] = profit
client_df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_cost,unit_weight,qty,line_number,subtotal_price,total_weight,shipping_price,total_price,total_cost,profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,762.71,7.50,105,1,115164.00,787.50,5512.50,121186.406250,85597.05,35589.356250
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,15.09,1.49,21,0,523.95,31.29,312.90,865.793250,629.79,236.003250
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,7.86,1.68,39,6,527.28,65.52,458.64,1028.344200,765.18,263.164200
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,24.85,1.23,29,3,1056.18,35.67,356.70,1445.874750,1077.35,368.524750
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,108.17,46.43,20,1,3902.00,928.60,6500.20,11003.468500,8663.60,2339.868500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,51.60,2.25,33,8,2743.29,74.25,519.75,3311.116875,2222.55,1088.566875
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,175.46,11.70,47,0,9709.73,549.90,3849.30,13915.090250,12095.92,1819.170250
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,57.31,4.16,475,6,31188.50,1976.00,13832.00,46299.960000,41054.25,5245.710000
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.22,18.04,112,0,165.76,2020.48,14143.36,15617.380800,14280.00,1337.380800
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,1.61,2.07,1031,5,3103.31,2134.17,14939.19,19424.375075,16599.10,2825.275075

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25

In [27]:
# Check your work using the totals above
verify = client_df.loc[(client_df['order_id']== 2742071)]
verify['total_price'].sum()

140990.45905

## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [ ]:
# How much did each of the top 5 clients by quantity
# spend? Check your work from Part 1 for client ids.

In [ ]:
# Create a summary DataFrame showing the totals for the
# for the top 5 clients with the following information:
# total units purchased, total shipping price,
# total revenue, and total profit. Sort by total profit.

In [ ]:
# Format the data and rename the columns
# to names suitable for presentation.
# Currency should be in millions of dollars.

In [ ]:
# Sort the updated data by "Total Profit" form highest to lowest